title: History 
description: This project tells 
baseurl: /kazakhwomen
url: https://happy-ayka.github.io
author: aigerim
email: aigerim@ucsb.edu
telar_theme: paisajes
logo: ''
telar_language: en
google_sheets:
  enabled: true
  shared_url: 'https://docs.google.com/spreadsheets/d/1hAXJargfR6-2oIetuUs_KMQqMUcsLJk04YDMAL_pB-0/edit?usp=sharing'
  published_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRoVRYTpkvGLmBPT_QJEC-aBqiGfZSnplaqpXWbgDCPMepWaAbixnd6PpY5HtLmNIT5zUlBD9HEQQhw/pubhtml'
markdown: kramdown
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- .github
- README.md
- docs/
- scripts/
collections_dir: _jekyll-files
collections:
  stories:
    output: true
    permalink: /stories/:name/
  objects:
    output: true
    permalink: /objects/:name/
  glossary:
    output: true
    permalink: /glossary/:name/
future: true
show_drafts: false
defaults:
- scope:
    path: ''
    type: stories
  values:
    layout: story
- scope:
    path: ''
    type: objects
  values:
    layout: object
- scope:
    path: ''
    type: glossary
  values:
    layout: glossary
telar:
  version: 0.3.4-beta
  release_date: $(date +%Y-%m-%d)
plugins:
- jekyll-seo-tag
webrick:
  headers:
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: GET, POST, OPTIONS
    Access-Control-Allow-Headers: Content-Type
